# If you have any process.env variables, this is where they should be specified.
runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
