service: timemap
runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html
   http_headers:
     Access-Control-Allow-Origin: http://datasheet-server-dot-forensic-265906.appspot.com/
 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
   http_headers:
    Access-Control-Allow-Origin: http://datasheet-server-dot-forensic-265906.appspot.com/